package ru.izotov.football

data class Parameters(
    val centerOfField: Point = Point(4,6),
    val gateOfPlayer1: Point = Point(4, 12),
    val gateOfPlayer2: Point = Point(4, 0),
    val borderLines: List<Line> = listOf(
        /*---------- top -------------*/
        Line(Point(0, 1), Point(1, 1)),
        Line(Point(1, 1), Point(2, 1)),
        Line(Point(2, 1), Point(3, 1)),
        Line(Point(3, 1), Point(3, 0)),
        Line(Point(3, 0), Point(4, 0)),
        Line(Point(4, 0), Point(5, 0)),
        Line(Point(5, 0), Point(5, 1)),
        Line(Point(5, 1), Point(6, 1)),
        Line(Point(6, 1), Point(7, 1)),
        Line(Point(7, 1), Point(8, 1)),
        /*---------- right -----------*/
        Line(Point(8, 1), Point(8, 2)),
        Line(Point(8, 2), Point(8, 3)),
        Line(Point(8, 3), Point(8, 4)),
        Line(Point(8, 4), Point(8, 5)),
        Line(Point(8, 5), Point(8, 6)),
        Line(Point(8, 6), Point(8, 7)),
        Line(Point(8, 7), Point(8, 8)),
        Line(Point(8, 8), Point(8, 9)),
        Line(Point(8, 9), Point(8, 10)),
        Line(Point(8, 10), Point(8, 11)),
        /*---------- bottom ----------*/
        Line(Point(0, 11), Point(1, 11)),
        Line(Point(1, 11), Point(2, 11)),
        Line(Point(2, 11), Point(3, 11)),
        Line(Point(3, 11), Point(3, 12)),
        Line(Point(3, 12), Point(4, 12)),
        Line(Point(4, 12), Point(5, 12)),
        Line(Point(5, 12), Point(5, 11)),
        Line(Point(5, 11), Point(6, 11)),
        Line(Point(6, 11), Point(7, 11)),
        Line(Point(7, 11), Point(8, 11)),
        /*---------- left ------------*/
        Line(Point(0, 1), Point(0, 2)),
        Line(Point(0, 2), Point(0, 3)),
        Line(Point(0, 3), Point(0, 4)),
        Line(Point(0, 4), Point(0, 5)),
        Line(Point(0, 5), Point(0, 6)),
        Line(Point(0, 6), Point(0, 7)),
        Line(Point(0, 7), Point(0, 8)),
        Line(Point(0, 8), Point(0, 9)),
        Line(Point(0, 9), Point(0, 10)),
        Line(Point(0, 10), Point(0, 11)),
        /*---------- middle -----------*/
        Line(Point(0, 6), Point(1, 6)),
        Line(Point(1, 6), Point(2, 6)),
        Line(Point(2, 6), Point(3, 6)),
        Line(Point(3, 6), Point(4, 6)),
        Line(Point(4, 6), Point(5, 6)),
        Line(Point(5, 6), Point(6, 6)),
        Line(Point(6, 6), Point(7, 6)),
        Line(Point(7, 6), Point(8, 6)),
    ),
    var borderPoints: MutableList<Point> = mutableListOf(
        /*---------- top -------------*/
        Point(0, 1),
        Point(1, 1),
        Point(2, 1),
        Point(3, 1),
        Point(3, 0),
        Point(4, 0),
        Point(5, 0),
        Point(5, 1),
        Point(6, 1),
        Point(7, 1),
        Point(8, 1),
        /*---------- right -----------*/
        Point(8, 2),
        Point(8, 3),
        Point(8, 4),
        Point(8, 5),
        Point(8, 6),
        Point(8, 7),
        Point(8, 8),
        Point(8, 9),
        Point(8, 10),
        /*---------- bottom ----------*/
        Point(0, 11),
        Point(1, 11),
        Point(2, 11),
        Point(3, 11),
        Point(3, 12),
        Point(4, 12),
        Point(5, 12),
        Point(5, 11),
        Point(6, 11),
        Point(7, 11),
        Point(8, 11),
        /*---------- left ------------*/
        Point(0, 2),
        Point(0, 3),
        Point(0, 4),
        Point(0, 5),
        Point(0, 6),
        Point(0, 7),
        Point(0, 8),
        Point(0, 9),
        Point(0, 10),
        /*---------- middle -----------*/
        Point(1, 6),
        Point(2, 6),
        Point(3, 6),
        Point(5, 6),
        Point(6, 6),
        Point(7, 6),
        Point(4, 6), // start
    ),
    val fieldPoints: List<Point> = listOf(
        gateOfPlayer1,
        gateOfPlayer2,

//        Point(0, 1), // corner
        Point(1, 1),
        Point(2, 1),
        Point(3, 1),
        Point(4, 1),
        Point(5, 1),
        Point(6, 1),
        Point(7, 1),
//        Point(8, 1), // corner
        
        Point(0, 2),
        Point(1, 2),
        Point(2, 2),
        Point(3, 2),
        Point(4, 2),
        Point(5, 2),
        Point(6, 2),
        Point(7, 2),
        Point(8, 2),
        
        Point(0, 3),
        Point(1, 3),
        Point(2, 3),
        Point(3, 3),
        Point(4, 3),
        Point(5, 3),
        Point(6, 3),
        Point(7, 3),
        Point(8, 3),
        
        Point(0, 4),
        Point(1, 4),
        Point(2, 4),
        Point(3, 4),
        Point(4, 4),
        Point(5, 4),
        Point(6, 4),
        Point(7, 4),
        Point(8, 4),
        
        Point(0, 5),
        Point(1, 5),
        Point(2, 5),
        Point(3, 5),
        Point(4, 5),
        Point(5, 5),
        Point(6, 5),
        Point(7, 5),
        Point(8, 5),
        
        Point(0, 6),
        Point(1, 6),
        Point(2, 6),
        Point(3, 6),
        Point(4, 6),
        Point(5, 6),
        Point(6, 6),
        Point(7, 6),
        Point(8, 6),
        
        Point(0, 7),
        Point(1, 7),
        Point(2, 7),
        Point(3, 7),
        Point(4, 7),
        Point(5, 7),
        Point(6, 7),
        Point(7, 7),
        Point(8, 7),
        
        Point(0, 8),
        Point(1, 8),
        Point(2, 8),
        Point(3, 8),
        Point(4, 8),
        Point(5, 8),
        Point(6, 8),
        Point(7, 8),
        Point(8, 8),
        
        Point(0, 9),
        Point(1, 9),
        Point(2, 9),
        Point(3, 9),
        Point(4, 9),
        Point(5, 9),
        Point(6, 9),
        Point(7, 9),
        Point(8, 9),
        
        Point(0, 10),
        Point(1, 10),
        Point(2, 10),
        Point(3, 10),
        Point(4, 10),
        Point(5, 10),
        Point(6, 10),
        Point(7, 10),
        Point(8, 10),

//        Point(0, 11), // corner
        Point(1, 11),
        Point(2, 11),
        Point(3, 11),
        Point(4, 11),
        Point(5, 11),
        Point(6, 11),
        Point(7, 11),
//        Point(8, 11), // corner
    )
)